WebDatLichKham/WebDatLichKham/DACS/Models/BacSi.cs
using static System.Net.Mime.MediaTypeNames;
using System.ComponentModel.DataAnnotations;
using DACS.Models;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations.Schema;
using WebDatLichKham.Models;

namespace DACS.Models
{
    public class BacSi
    {
        public int Id { get; set; }
        public string Name { get; set; }
        [StringLength(6)]
        public string GioiTinh { get; set; }
        public int? ChucVuId { get; set; }
        public int? KhoaId { get; set; }
        public DateTime NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string? GioiThieu { get; set; }
        public string? KinhNghiem { get; set; }
        public string? HocVan { get; set; }

        public string? ImageUrl { get; set; }

        public  ChucVu? ChucVu { get; set; }
        public  Khoa? Khoa { get; set; }

        public  ICollection<Image> Images { get; set; }
        public  ICollection<ChiTietDatLichKham> ChiTietLichKhamBenhs { get; set; }
        public  ICollection<LichLamViec> LichLamViecs { get; set; }
        [ForeignKey("UserId")]
        [ValidateNever]
        public ApplicationUser? ApplicationUser { get; set; }

    }
}

WebDatLichKham/WebDatLichKham/DACS/Controllers/BacSisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DACS.Data;
using DACS.Models;
using WebDatLichKham.Repositories;
using WebDatLichKham.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;

namespace DACS.Controllers
{
    public class BacSisController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IEmailService _emailService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ZaloService _zaloService;
        private readonly ILogger<BacSisController> _logger;
        public BacSisController(ApplicationDbContext context, IEmailService emailService, UserManager<ApplicationUser> userManager, ZaloService zaloService, ILogger<BacSisController> logger)
        {
            _context = context;
            _emailService = emailService;
            _userManager = userManager;
            _zaloService = zaloService;
            _logger = logger;
        }

        // GET: BacSis
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.BacSis.Include(b => b.ChucVu).Include(b => b.Khoa);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: BacSis/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bacSi = await _context.BacSis
                .Include(b => b.ChucVu)
                .Include(b => b.Khoa)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bacSi == null)
            {
                return NotFound();
            }

            return View(bacSi);
        }
        //GET: hiển thị thông tin bác sĩ chọn ngày và hiển thị ca làm việc của bác sĩ
        [HttpGet]
        public async Task<IActionResult> GetWorkSchedules(int doctorId, DateTime selectedDate)
        {
            var workSchedules = await _context.LichLamViecs
                .Where(w => w.BacSiId == doctorId && w.Lich == selectedDate.Date)
                .ToListAsync();
         
            if (workSchedules == null || !workSchedules.Any())
            {

                ViewBag.ErrorMessage = "Không tìm thấy lịch làm việc.";
                return PartialView("_WorkSchedules", Enumerable.Empty<LichLamViec>());
            }

            return PartialView("_WorkSchedules", workSchedules);
        }
        [HttpPost]
        public async Task<IActionResult> SetTime(int lichId, string time)
        {
            // Tìm lịch làm việc theo Id
            var lichLamViec = await _context.LichLamViecs.FindAsync(lichId);

            if (lichLamViec == null)
            {
                return NotFound();
            }

            // Xử lý thời gian
            var ca = TimeOnly.Parse(time);

            //Kiểm tra xem có cuộc hẹn nào vào thời gian đã chọn không
            var datLichKham = await _context.DatLichKhams
                .FirstOrDefaultAsync(d => d.LichLamViecId == lichId && d.LichLamViec.Ca == ca);

            if (datLichKham != null)
            {
                return BadRequest("Thời gian đã được chọn không khả dụng.");
            }
            else
            {
                // Trả về thông tin lịch làm việc đã chọn cùng với danh sách ca làm việc
                var caLamViecs = await _context.LichLamViecs.Where(l => l.Id == lichId).ToListAsync();
                return Ok(caLamViecs);
            }
        }

        // GET: BacSis/Create
        public IActionResult Create()
        {
            ViewData["ChucVuId"] = new SelectList(_context.ChucVus, "Id", "Id");
            ViewData["KhoaId"] = new SelectList(_context.Khoas, "Id", "Id");
            return View();
        }

        // POST: BacSis/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,GioiTinh,ChucVuId,KhoaId,NgaySinh,DiaChi,SoDienThoai,GioiThieu,KinhNghiem,HocVan,ImageUrl")] BacSi bacSi)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bacSi);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ChucVuId"] = new SelectList(_context.ChucVus, "Id", "Id", bacSi.ChucVuId);
            ViewData["KhoaId"] = new SelectList(_context.Khoas, "Id", "Id", bacSi.KhoaId);
            return View(bacSi);
        }

        // GET: BacSis/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bacSi = await _context.BacSis.FindAsync(id);
            if (bacSi == null)
            {
                return NotFound();
            }
            ViewData["ChucVuId"] = new SelectList(_context.ChucVus, "Id", "Id", bacSi.ChucVuId);
            ViewData["KhoaId"] = new SelectList(_context.Khoas, "Id", "Id", bacSi.KhoaId);
            return View(bacSi);
        }

        // POST: BacSis/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,GioiTinh,ChucVuId,KhoaId,NgaySinh,DiaChi,SoDienThoai,GioiThieu,KinhNghiem,HocVan,ImageUrl")] BacSi bacSi)
        {
            if (id != bacSi.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bacSi);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BacSiExists(bacSi.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ChucVuId"] = new SelectList(_context.ChucVus, "Id", "Id", bacSi.ChucVuId);
            ViewData["KhoaId"] = new SelectList(_context.Khoas, "Id", "Id", bacSi.KhoaId);
            return View(bacSi);
        }

        // GET: BacSis/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bacSi = await _context.BacSis
                .Include(b => b.ChucVu)
                .Include(b => b.Khoa)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bacSi == null)
            {
                return NotFound();
            }

            return View(bacSi);
        }

        // POST: BacSis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bacSi = await _context.BacSis.FindAsync(id);
            if (bacSi != null)
            {
                _context.BacSis.Remove(bacSi);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BacSiExists(int id)
        {
            return _context.BacSis.Any(e => e.Id == id);
        }


        [HttpGet]
        public IActionResult NhapThongTinBenhNhan(int? lichId)
        {
            if (lichId == null)
            {
                return NotFound();
            }

            // Lấy thông tin lịch làm việc để truyền vào view
            var lichLamViec = _context.LichLamViecs
                                    .Include(l => l.BacSi) // Bao gồm thông tin bác sĩ
                                    .FirstOrDefault(l => l.Id == lichId);
            if (lichLamViec == null)
            {
                return NotFound();
            }

            ViewBag.LichId = lichId;
            ViewBag.BacSi = lichLamViec.BacSi;
            ViewBag.LichLamViec = lichLamViec;
            ViewBag.Ca = lichLamViec.Ca;
            ViewBag.Lich = lichLamViec.Lich;

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> NhapThongTinBenhNhan(string Name, string GioiTinh, DateTime NgaySinh, string DiaChi, string SoDienThoai, List<IFormFile> imageUrls, int lichId, string Gmail, string TinhTrang)
        {
            if (ModelState.IsValid)
            {
                var benhNhan = new BenhNhan
                {
                    Name = Name,
                    GioiTinh = GioiTinh,
                    NgaySinh = NgaySinh,
                    DiaChi = DiaChi,
                    SoDienThoai = SoDienThoai,
                    TinhTrang = TinhTrang,
                    Gmail = Gmail,
                };

                foreach (var image in imageUrls)
                {
                    var imagePath = await SaveImage(image);
                    benhNhan.Images.Add(new Image { ImageUrl = imagePath, Name = image.FileName });
                }

                _context.BenhNhans.Add(benhNhan);
                await _context.SaveChangesAsync();

                var datLichKham = new DatLichKham
                {
                    BenhNhanId = benhNhan.Id,
                    LichLamViecId = lichId,
                    NgayDatLich = DateTime.Now,

WebDatLichKham/WebDatLichKham/DACS/Views/BacSis/Create.cshtml
@model DACS.Models.BacSi

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>BacSi</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GioiTinh" class="control-label"></label>
                <input asp-for="GioiTinh" class="form-control" />
                <span asp-validation-for="GioiTinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChucVuId" class="control-label"></label>
                <select asp-for="ChucVuId" class ="form-control" asp-items="ViewBag.ChucVuId"></select>
            </div>
            <div class="form-group">
                <label asp-for="KhoaId" class="control-label"></label>
                <select asp-for="KhoaId" class ="form-control" asp-items="ViewBag.KhoaId"></select>
            </div>
            <div class="form-group">
                <label asp-for="NgaySinh" class="control-label"></label>
                <input asp-for="NgaySinh" class="form-control" />
                <span asp-validation-for="NgaySinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiaChi" class="control-label"></label>
                <input asp-for="DiaChi" class="form-control" />
                <span asp-validation-for="DiaChi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoDienThoai" class="control-label"></label>
                <input asp-for="SoDienThoai" class="form-control" />
                <span asp-validation-for="SoDienThoai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GioiThieu" class="control-label"></label>
                <input asp-for="GioiThieu" class="form-control" />
                <span asp-validation-for="GioiThieu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KinhNghiem" class="control-label"></label>
                <input asp-for="KinhNghiem" class="form-control" />
                <span asp-validation-for="KinhNghiem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HocVan" class="control-label"></label>
                <input asp-for="HocVan" class="form-control" />
                <span asp-validation-for="HocVan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebDatLichKham/WebDatLichKham/DACS/Views/BacSis/Delete.cshtml
@model DACS.Models.BacSi

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BacSi</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NgaySinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DiaChi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoDienThoai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoDienThoai)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GioiThieu)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GioiThieu)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KinhNghiem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KinhNghiem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HocVan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HocVan)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChucVu)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChucVu.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Khoa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Khoa.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebDatLichKham/WebDatLichKham/DACS/Views/BacSis/Details.cshtml
@model DACS.Models.BacSi

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    body {
        font-family: 'Roboto', Arial, sans-serif;
        line-height: 1.6;
        color: #333;
        background-color: #f8f9fa;
    }

    .container2 {
        padding: 100px;
    }

    .breadcrumb {
        background-color: #f8f9fa;
        padding: 0;
        margin-bottom: 20px;
    }

    .breadcrumb-item a {
        color: #007bff;
    }

    .breadcrumb-item.active {
        color: #6c757d;
    }

    .card {
        background-color: #fff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        margin-bottom: 20px;
    }

    .doctor-name {
        color: black;
        font-size: 2rem;
        margin-bottom: 10px;
        font-weight: bold;
    }

    .doctor-title {
        font-size: 1.25rem;
        color: #6c757d;
        margin-bottom: 10px;
    }

    .doctor-location, .doctor-fee {
        font-size: 1rem;
        color: #6c757d;
        margin-bottom: 10px;
    }

    .back-to-home a {
        background-color: black;
        color: #fff;
        padding: 10px 20px;
        border-radius: 5px;
        text-decoration: none;
    }

        .back-to-home a:hover {
            background-color: #0056b3;
        }

    .img-fluid {
        max-width: 75%;
        height: auto;
    }

    .rounded-circle {
        border-radius: 50% !important;
    }

    .schedule-list {
        display: flex;
        flex-wrap: wrap;
        gap: 10px;
    }

    .schedule-item {
        flex: 1 1 calc(33.333% - 10px);
        padding: 10px;
        background-color: #e9ecef;
        border-radius: 8px;
        text-align: center;
    }

    .outer-box {
        border: 2px solid #007bff;
        border-radius: 10px;
        padding: 100px;
        background-color: #ffffff;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }
</style>

<div class="container2 outer-box">
    <div class="row">
        <div class="col-md-12">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="@Url.Action("Datlich", "Home")">Trang Chủ</a></li>
                    <li class="breadcrumb-item active" aria-current="page">@Model.Name</li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <img src="@Model.ImageUrl" alt="Doctor profile picture" class="img-fluid rounded-circle" />
        </div>
        <div class="col-md-6">
            <h1 class="doctor-name">@Model.Name</h1>
            <p class="doctor-title">Chức vụ: @Model.ChucVu.Name</p>
            <p class="doctor-location"><i class="fas fa-map-marker-alt"></i> Chuyên khoa: @Model.Khoa.Name</p>
            <p class="doctor-fee">@Model.KinhNghiem</p>
        </div>
        <div class="col-md-3">
            <!-- Add any additional information or buttons if needed -->
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <h4>Chọn ngày khám</h4>
                <input type="date" id="selectedDate" name="selectedDate" class="form-control" onchange="loadSchedules(this.value)" />
                <div id="scheduleList" class="schedule-list mt-3"></div>
            </div>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-md-12">
            <div class="card">
                <h4>Thông tin bác sĩ</h4>
                <p>@Model.GioiThieu</p>
                <h4>Quá trình đào tạo</h4>
                <p>@Model.KinhNghiem</p>
            </div>
        </div>
    </div>
</div>

<!-- Modal for appointment form -->
<div class="modal fade" id="infoModal" tabindex="-1" role="dialog" aria-labelledby="infoModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="infoModalLabel">Thông tin đặt lịch khám bệnh</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="infoModalBody">
                <!-- Form content will be loaded here via AJAX -->
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        function loadSchedules(selectedDate) {
            var bacsiId = @Model.Id;
            var url = '@Url.Action("GetWorkSchedules", "BacSis")' + `?doctorId=${bacsiId}&selectedDate=${selectedDate}`;
            $.get(url, function (data) {
                $('#scheduleList').html(data);
            });
        }
    </script>
}

WebDatLichKham/WebDatLichKham/DACS/Views/BacSis/Edit.cshtml
@model DACS.Models.BacSi

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>BacSi</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GioiTinh" class="control-label"></label>
                <input asp-for="GioiTinh" class="form-control" />
                <span asp-validation-for="GioiTinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChucVuId" class="control-label"></label>
                <select asp-for="ChucVuId" class="form-control" asp-items="ViewBag.ChucVuId"></select>
                <span asp-validation-for="ChucVuId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KhoaId" class="control-label"></label>
                <select asp-for="KhoaId" class="form-control" asp-items="ViewBag.KhoaId"></select>
                <span asp-validation-for="KhoaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgaySinh" class="control-label"></label>
                <input asp-for="NgaySinh" class="form-control" />
                <span asp-validation-for="NgaySinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiaChi" class="control-label"></label>
                <input asp-for="DiaChi" class="form-control" />
                <span asp-validation-for="DiaChi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoDienThoai" class="control-label"></label>
                <input asp-for="SoDienThoai" class="form-control" />
                <span asp-validation-for="SoDienThoai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GioiThieu" class="control-label"></label>
                <input asp-for="GioiThieu" class="form-control" />
                <span asp-validation-for="GioiThieu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KinhNghiem" class="control-label"></label>
                <input asp-for="KinhNghiem" class="form-control" />
                <span asp-validation-for="KinhNghiem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HocVan" class="control-label"></label>
                <input asp-for="HocVan" class="form-control" />
                <span asp-validation-for="HocVan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebDatLichKham/WebDatLichKham/DACS/Views/BacSis/Index.cshtml
@model IEnumerable<DACS.Models.BacSi>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GioiTinh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NgaySinh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DiaChi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoDienThoai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GioiThieu)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.KinhNghiem)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HocVan)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ChucVu)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Khoa)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GioiTinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgaySinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaChi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoDienThoai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GioiThieu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KinhNghiem)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HocVan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImageUrl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ChucVu.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Khoa.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
               
            </td>
        </tr>
}
    </tbody>
</table>